#index: #nom de route
#    path: /home #path 
#    controller: App\Controller\HomeController::index #nom de controlleur + nom de fonction qui va le  pointer dans le controlleur 
    
firstPage:
    path: /firstPage
    controller: App\Controller\FirstPageController::index.

#redirectTo:
#    path: /hello
#    controller: App\Controller\HomeController::hello
